# Generated by Django 4.1.7 on 2023-04-06 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='alltime_rank',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Wins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourney_wins', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.player')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
