# Generated by Django 4.1.7 on 2023-04-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_player_alltime_rank_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wins',
            name='tourney_wins',
            field=models.CharField(max_length=100),
        ),
    ]
