# Generated by Django 4.1.7 on 2023-04-11 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_character_remove_player_character_player_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wins',
            new_name='Win',
        ),
    ]
